### PR TITLE
Update how-to-build-and-publish-es6-npm-modules-today-with-babel.md

### PR DESCRIPTION
**Pull request by s-moon**
Very minor changes including some which are my personal taste (position of commas).

### CODE REVIEW

**Comment by bookercodes** [comment]
Wow. I am embarrassed by those spelling mistakes.

**Comment by bookercodes** [comment]
Thanks for this. I updated the post to gave you special mention, of course :smile:

**Comment by s-moon** [comment]
No worries. I'm really plsd to c u writing. I think its an important facet in building ur 'brand'. Hows the live coding going?

-----Original Message-----

**Comment by s-moon** [comment]
Alex, which tool do u use to make animated gifs? Saw one on ur github which looked great.

-----Original Message-----

**Comment by bookercodes** [comment]
@s-moon Camtasia Studio!

**Pull request merged**
